# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('game_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
